dataset:
  name: retina
  image_dir: ${hydra:runtime.cwd}/data/Retina/Data/train/image
  mask_dir:  ${hydra:runtime.cwd}/data/Retina/Data/train/mask
  pin_memory: true
  image_size: [512, 512]

training:
  mode: finetune
  batch_size: 32
  num_workers: 8
  lr: 1e-4
  epochs: 200
  ckpt_dir: ${hydra:runtime.cwd}/checkpoints
  pretrained_path: ${hydra:runtime.cwd}/checkpoints/unet-transition/best_model.pth
  freeze_encoder: true

evaluation:
  batch_size: 64

wandb:
  project: breast-unet
  run_name: unet-finetune-retina-transition
  enable: true
